name: MonitorBlock
version: 1.0
main: com.pepino.monitorblock.MonitorBlock
api-version: 1.20
commands:
  monitorblock:
    description: Gives you a MonitorBlock wand to monitor blocks
    usage: /monitorblock <name>
    permission: monitorblock.use
    permission-message: You do not have permission to use this command.
permissions:
  monitorblock.use:
    description: Allows the use of the /monitorblock command.
    default: op
